kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/lrills/helm-unittest/

steps:
  - name: build
    image: golang:1.12
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - mkdir /go/bin
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - dep ensure
      - make dist
  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - _dist/*
      checksum:
        - sha256
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
